### ISSUE TITLE
Documentation example does not match actual API

### ISSUE THREAD

**Issue by MarkAWard** [newrelic/newrelic-python-agent#11]
**Description**
The Example provided in the docs [here](https://docs.newrelic.com/docs/agents/python-agent/python-agent-api/addcustomparameters-python-agent-api) does not match the actual required parameter type. The Parameters says one must pass a list of tuples yet the Example given passes a dict, which would raise `exceptions:ValueError: too many values to unpack`. Unfortunately, we have fallen victim to writing our code based off of the example more times than I would like to admit.

**Expected Behavior**
1. A valid example such as:
```
@newrelic.agent.background_task()
def send_request(): 
	response = requests.post('http://URL_path', headers=headers, data=data) 
	newrelic.agent.add_custom_parameters([
                ('url_path_status_code', response.status_code),
        ]) 
```
2. Potentially, a misuse of the SDK does no totally fail code execution but could notify the user of the error loudly. Similar to how the logging module is implemented:
```
In [8]: def dont_kill_my_code(): 
   ...:     logger.info("bad data %d", "not a digit") 
   ...:     print("I made it here still") 
   ...:                                                                                                                                                                                                     

In [9]: dont_kill_my_code()                                                                                                                                                                                 
--- Logging error ---
Traceback (most recent call last):
  File "/Users/markward/anaconda2/envs/pollen/lib/python3.8/logging/__init__.py", line 1081, in emit
    msg = self.format(record)
  File "/Users/markward/anaconda2/envs/pollen/lib/python3.8/logging/__init__.py", line 925, in format
    return fmt.format(record)
  File "/Users/markward/anaconda2/envs/pollen/lib/python3.8/logging/__init__.py", line 664, in format
    record.message = record.getMessage()
  File "/Users/markward/anaconda2/envs/pollen/lib/python3.8/logging/__init__.py", line 369, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not str
Call stack:
  File "/Users/markward/anaconda2/envs/pollen/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/Users/markward/anaconda2/envs/pollen/lib/python3.8/site-packages/IPython/__init__.py", line 126, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/markward/anaconda2/envs/pollen/lib/python3.8/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/Users/markward/anaconda2/envs/pollen/lib/python3.8/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/Users/markward/anaconda2/envs/pollen/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 563, in mainloop
    self.interact()
  File "/Users/markward/anaconda2/envs/pollen/lib/python3.8/site-packages/IPython/terminal/interactiveshell.py", line 554, in interact
    self.run_cell(code, store_history=True)
  File "/Users/markward/anaconda2/envs/pollen/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2866, in run_cell
    result = self._run_cell(
  File "/Users/markward/anaconda2/envs/pollen/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2895, in _run_cell
    return runner(coro)
  File "/Users/markward/anaconda2/envs/pollen/lib/python3.8/site-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/Users/markward/anaconda2/envs/pollen/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3071, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/Users/markward/anaconda2/envs/pollen/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3263, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/Users/markward/anaconda2/envs/pollen/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-405f0f64a064>", line 1, in <module>
    dont_kill_my_code()
  File "<ipython-input-8-45cf361c5300>", line 2, in dont_kill_my_code
    logger.info("bad data %d", "not a digit")
Message: 'bad data %d'
Arguments: ('not a digit',)
I made it here still
```

**Comment by carrieedwards** [comment]
Hi @MarkAWard, 

Thank you so much for filing this issue! We greatly appreciate the feedback. The documentation has been updated to reflect an example that passes in a list. Please feel free to file issues for any inconsistent documentation that you encounter. 

We are sorry to hear about invalid inputs crashes in your application, and we appreciate your suggestion.  We will close this issue for now since the documentation issue has been addressed, but if this continues to be a problem, please reopen the ticket.
