### ISSUE TITLE
Setting log_file = stderr in the config logs an error

### ISSUE THREAD

**Issue by rittneje** [newrelic/newrelic-python-agent#299]
We explicitly set `log_file = stderr` in our config file, as described here. https://docs.newrelic.com/docs/agents/python-agent/configuration/python-agent-configuration/#log_file

However, doing so causes the agent to log an error message at startup.
> 2021-07-28 18:50:19,931 (62/MainThread) newrelic ERROR - Falling back to stderr logging as unable to create log file <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/newrelic/common/log_file.py", line 94, in initialize_logging
    _initialize_file_logging(log_file, log_level)
  File "/usr/local/lib/python3.9/site-packages/newrelic/common/log_file.py", line 66, in _initialize_file_logging
    handler = logging.FileHandler(log_file)
  File "/usr/local/lib/python3.9/logging/__init__.py", line 1132, in __init__
    filename = os.fspath(filename)
TypeError: expected str, bytes or os.PathLike object, not TextIOWrapper

This is with v6.4.4.161.

**Comment by rittneje** [comment]
Turns out the developer accidentally wrote `log_file=stderr` rather than `log_file="stderr"` in the call to `initialize`.
