### ISSUE TITLE
NR Dependency Protobuf 3.18.0 Not Compatible With Python 2.7

### ISSUE THREAD

**Issue by ragle** [newrelic/newrelic-python-agent#404]
May not be the right place for this, but hopefully it helps someone with the same issue. 

**Description**

```text
Traceback (most recent call last):
  File "xxx/utils.py", line 4, in <module>
    import newrelic.agent
  File "/xxx/lib/python2.7/site-packages/newrelic/agent.py", line 15, in <module>
    from newrelic.config import (
  File "/xxx/lib/python2.7/site-packages/newrelic/config.py", line 30, in <module>
    from newrelic.core.config import (Settings, apply_config_setting,
  File "xxx/lib/python2.7/site-packages/newrelic/core/config.py", line 43, in <module>
    from newrelic.core.infinite_tracing_pb2 import Span as _  # NOQA
  File "xxx/lib/python2.7/site-packages/newrelic/core/infinite_tracing_pb2.py", line 16, in <module>
    from google.protobuf import descriptor as _descriptor
  File "xxx/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 113
    class DescriptorBase(metaclass=DescriptorMetaclass):
                                  ^
SyntaxError: invalid syntax
```

See: [https://issueexplorer.com/issue/GoogleCloudPlatform/python-docs-samples/6703](https://issueexplorer.com/issue/GoogleCloudPlatform/python-docs-samples/6703)

**Steps to Reproduce**

In a python 2.7 env: 

`pip install newrelic==6.2.0.156`

`$ python`

`>>> import newrelic.agent`

**Your Environment**

*  Python 2.7 
*  newrelic==6.2.0.156

**Additional context**

Rolling back to `protobuf~=3.17.3` fixes this.

**Comment by TimPansino** [comment]
Yes thank you, that's the correct issue. I was looking for the link earlier and didn't find it, was looking at gRPC not protobuf.
