### ISSUE TITLE
Fix Python 3.11 support

### ISSUE THREAD

**Issue by stianjensen** [newrelic/newrelic-python-agent#637]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

**Description**
Python 3.11 is due to be released as a stable version on October 24th (a little under a month from now).
I'm currently performing compatibility and performance testing in order to be ready for the release, but at the moment I'm unable to perform a full staging test, since the newrelic package crashes.

<details>
<summary><b>Click here to show traceback</b></summary>

```python
Traceback (most recent call last):
  File "/Users/stiaje/.pyenv/versions/3.11.0b3/lib/python3.11/logging/config.py", line 562, in configure
    handler = self.configure_handler(handlers[name])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stiaje/.pyenv/versions/3.11.0b3/lib/python3.11/logging/config.py", line 747, in configure_handler
    result = factory(**kwargs)
             ^^^^^^^^^^^^^^^^^
  File "/Users/stiaje/Projects/django-backend/app/.venv/lib/python3.11/site-packages/django/utils/log.py", line 90, in __init__
    self.reporter_class = import_string(
                          ^^^^^^^^^^^^^^
  File "/Users/stiaje/Projects/django-backend/app/.venv/lib/python3.11/site-packages/django/utils/module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stiaje/Projects/django-backend/app/.venv/lib/python3.11/site-packages/django/utils/module_loading.py", line 15, in cached_import
    import_module(module_path)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stiaje/.pyenv/versions/3.11.0b3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 939, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/stiaje/Projects/django-backend/app/hyre/utils/log.py", line 10, in <module>
    import newrelic.agent
    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stiaje/Projects/django-backend/app/.venv/lib/python3.11/site-packages/newrelic/agent.py", line 15, in <module>
    from newrelic.config import (
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stiaje/Projects/django-backend/app/.venv/lib/python3.11/site-packages/newrelic/config.py", line 26, in <module>
    import newrelic.api.application
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stiaje/Projects/django-backend/app/.venv/lib/python3.11/site-packages/newrelic/api/application.py", line 19, in <module>
    import newrelic.core.agent
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stiaje/Projects/django-backend/app/.venv/lib/python3.11/site-packages/newrelic/core/agent.py", line 33, in <module>
    import newrelic.core.application
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stiaje/Projects/django-backend/app/.venv/lib/python3.11/site-packages/newrelic/core/application.py", line 34, in <module>
    from newrelic.core.data_collector import create_session
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stiaje/Projects/django-backend/app/.venv/lib/python3.11/site-packages/newrelic/core/data_collector.py", line 23, in <module>
    from newrelic.common.agent_http import (
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stiaje/Projects/django-backend/app/.venv/lib/python3.11/site-packages/newrelic/common/agent_http.py", line 28, in <module>
    from newrelic.common.object_wrapper import patch_function_wrapper
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stiaje/Projects/django-backend/app/.venv/lib/python3.11/site-packages/newrelic/common/object_wrapper.py", line 27, in <module>
    from newrelic.packages.wrapt import (ObjectProxy as _ObjectProxy,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stiaje/Projects/django-backend/app/.venv/lib/python3.11/site-packages/newrelic/packages/wrapt/__init__.py", line 10, in <module>
    from .decorators import (adapter_factory, AdapterFactory, decorator,
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/stiaje/Projects/django-backend/app/.venv/lib/python3.11/site-packages/newrelic/packages/wrapt/decorators.py", line 34, in <module>
    from inspect import ismethod, isclass, formatargspec
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: cannot import name 'formatargspec' from 'inspect' (/Users/stiaje/.pyenv/versions/3.11.0b3/lib/python3.11/inspect.py)
```
</details>

**Expected Behavior**
I want to be able to install the newrelic package in Python 3.11

**[Troubleshooting](https://discuss.newrelic.com/t/troubleshooting-frameworks/108787) or [NR Diag](https://docs.newrelic.com/docs/using-new-relic/cross-product-functions/troubleshooting/new-relic-diagnostics) results**
[NOTE]: # ( Provide any other relevant log data. )
[TIP]:  # ( Scrub logs and diagnostic information for sensitive information )

**Steps to Reproduce**
- Setup a basic Django project with any of the latest release candidates of Python 3.11.
- Install New Relic
- Start the project

**Your Environment**
MacOS
Python 3.11.0b3
New Relic 8.0.0.179

**Additional context**
Previous related issue which have fixed a simlar issue, just not this one final place:
https://github.com/newrelic/newrelic-python-agent/issues/22
https://github.com/newrelic/newrelic-python-agent/issues/476

Removal of formatargspec: https://docs.python.org/3.11/whatsnew/3.11.html#removed
Python 3.11 release: https://www.python.org/downloads/release/python-3110rc2/

I've tried looking at creating a PR to fix the issue myself, but I've not been able to fully understand how `formatargspec` is being used, and what the replacement should look like exactly. It is hopefully easier for someone familiar with the codebase!

**Comment by TimPansino** [comment]
Ah, that's actually in a package we vendor (wrapt). Not in the agent code. I'll update it for our next release.
