### ISSUE TITLE
Can we mark code to be ignored by newrelic?

### ISSUE THREAD

**Issue by lukehsiao** [newrelic/newrelic-python-agent#824]
NewRelic is incompatible with Ray. Can we ignore Ray files?

**Description**
We have a FastAPI app that also includes [ray](https://github.com/ray-project/ray). When we run `newrelic-admin run-program uvicorn main:app`, we get an error similar to the following:

```
Traceback (most recent call last):
  File "/home/lukehsiao/repo/.venv/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/lukehsiao/repo/.venv/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/lukehsiao/repo/.venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/lukehsiao/repo/.venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lukehsiao/repo/.venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/lukehsiao/repo/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 410, in main
    run(
  File "/home/lukehsiao/repo/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/home/lukehsiao/repo/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/lukehsiao/.pyenv/versions/3.10.11/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/lukehsiao/repo/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/home/lukehsiao/repo/.venv/lib/python3.10/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/lukehsiao/repo/.venv/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/lukehsiao/.pyenv/versions/3.10.11/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  (...)
  File "/home/lukehsiao/repo/.venv/lib/python3.10/site-packages/ray/serve/api.py", line 198, in decorator
    frozen_app = cloudpickle.loads(cloudpickle.dumps(app))
  File "/home/lukehsiao/repo/.venv/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 88, in dumps
    cp.dump(obj)
  File "/home/lukehsiao/repo/.venv/lib/python3.10/site-packages/ray/cloudpickle/cloudpickle_fast.py", line 733, in dump
    return Pickler.dump(self, obj)
NotImplementedError: object proxy must define __reduce_ex__()
```
This seems somewhat expected, based on https://github.com/ray-project/ray/issues/27494.

The difference here is, _we do not need newrelic to try and instrument this code_. Ideally, we could use newrelic, but mark certain files to be ignored. 

Is this possible?

**Comment by lrafeei** [comment]
Hello--files themselves cannot be singled out, but there might be a few options:

1. Using `newrelic.agent.ignore_transaction(flag=True)` in the function that you want to avoid using with New Relic.  Example of usage [shown here](https://docs.newrelic.com/docs/apm/agents/python-agent/python-agent-api/ignoretransaction-python-agent-api/#ignore-example)
2. Does every FastAPI instance also use `ray.serve` or just some?  If it is all FastAPI functions, you can disable instrumentation for FastAPI by putting this in your config file: 
```
[import-hook:fastapi.routing]
enabled = false
```

However, I am not quite sure how to replicate this.  I tried the example code from the issue that was linked from here, but I got an error stemming from `ray.serve` instead.  If neither of these options works for you, could you provide a code snippet and a pip freeze that produced the traceback above?

**Comment by lukehsiao** [comment]
We found a workaround for now.

One way to effectively "hide" the 2nd FastAPI instrumentation is to wrap it in a function.

That is, our main FastAPI app has the standard

```py
from fastapi import FastAPI

app = FastAPI(...)
```

And our Ray serve instance changed from looking like

```py
from fastapi import FastAPI

app = FastAPI(...)

@serve.deployment()
@serve.ingress(app)
class Inference:
...
```

to

```py

def get_ray_serve():
    app = FastAPI()

    @serve.deployment()
    @serve.ingress(app)
    class Inference:
        ...

    return Inference

```

It seems wrapping it this way avoids new-relic from trying to auto-instrument the ray fastapi.

**Comment by lukehsiao** [comment]
I think it is fair to close this issue for now :).
