### ISSUE TITLE
Django graphql queries failing with APM agent installed with error bind_resolve_field_v3() takes 4 positional arguments but 6 were given

### ISSUE THREAD

**Issue by peteror** [newrelic/newrelic-python-agent#933]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

**Description**
I have a Django app with gunicorn and uvicornWorker ASGI async events. I run it on AWS ECS Fargate, with the infrastructure agent already installed for a while. I tried to add APM , as described [here](https://docs.newrelic.com/install/python/?python-non-web=non-web-no&python-docker=docker-yes&python-framework=unsupported-wsgi-framework&python-server=gunicorn ) (creating a container with the New Relic python agent and building my app container using that as a base)

The application is running, and I see APM data in New Relic; however, async events seem to be broken with the error log below. 

**Expected Behavior**
The app should run as before with APM data transmitted.

**Steps to Reproduce**
I'm using the Saleor e-commerce application, which is a Django app and starts with the 
gunicorn --bind :8000 --workers 4 --keep-alive 65 --worker-class saleor.asgi.gunicorn_worker.UvicornWorker saleor.asgi:application 
command

**Your Environment**
I run it on AWS ECS Fargate, with the infrastructure agent already installed. I'm using the latest NewRelic agent and python:3.9 as the base image.

**Error log**

{"asctime": "2023-10-07T07:30:30Z", "levelname": "ERROR", "lineno": 401, "message": "A query failed unexpectedly", "name": "saleor.graphql.errors.unhandled", "pathname": "/app/saleor/graphql/views.py", "process": 25, "threadName": "ThreadPoolExecutor-1_0", "exc_info": "Traceback (most recent call last):

 File "/usr/local/lib/python3.9/site-packages/newrelic/hooks/framework_graphql.py", line 368, in wrap_resolve_field

 parent_type, field_asts, field_path = bind_resolve_field(*args, **kwargs)

TypeError: bind_resolve_field_v3() takes 4 positional arguments but 6 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

 File "/usr/local/lib/python3.9/site-packages/newrelic/hooks/framework_graphql.py", line 368, in wrap_resolve_field

 parent_type, field_asts, field_path = bind_resolve_field(*args, **kwargs)

TypeError: bind_resolve_field_v3() takes 4 positional arguments but 6 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

 File "/usr/local/lib/python3.9/site-packages/newrelic/hooks/framework_graphql.py", line 368, in wrap_resolve_field

 parent_type, field_asts, field_path = bind_resolve_field(*args, **kwargs)

TypeError: bind_resolve_field_v3() takes 4 positional arguments but 6 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

 File "/usr/local/lib/python3.9/site-packages/newrelic/hooks/framework_graphql.py", line 368, in wrap_resolve_field

 parent_type, field_asts, field_path = bind_resolve_field(*args, **kwargs)

TypeError: bind_resolve_field_v3() takes 4 positional arguments but 6 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

 File "/usr/local/lib/python3.9/site-packages/graphql/execution/executor.py", line 480, in complete_value_catching_error

 completed = complete_value(

 File "/usr/local/lib/python3.9/site-packages/graphql/execution/executor.py", line 530, in complete_value

 return Promise.resolve(result).then(

 File "/usr/local/lib/python3.9/site-packages/promise/promise.py", line 737, in resolve

 return cls._try_convert_to_promise(obj)

 File "/usr/local/lib/python3.9/site-packages/promise/promise.py", line 697, in _try_convert_to_promise

 obj = ensure_future(obj) # type: ignore

 File "/usr/local/lib/python3.9/asyncio/tasks.py", line 664, in ensure_future

 loop = events.get_event_loop()

 File "/usr/local/lib/python3.9/asyncio/events.py", line 642, in get_event_loop

 raise RuntimeError('There is no current event loop in thread %r.'

RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-1_0'.", "hostname": "*****"}

**Comment by peteror** [comment]
update: looks like the issue was that the newrelic python agent dropped graphql-core v2 support from 9.00 - it works well with agent v 8.11

**Comment by hmstepanek** [comment]
It sounds like the issue was that the version of the agent that was being used didn't support graphql-core v2 so I'm closing this issue as a won't fix.
